---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: hyperdisk-ml
parameters:
    type: hyperdisk-ml
    provisioned-throughput-on-create: "50000Mi"
provisioner: pd.csi.storage.gke.io
allowVolumeExpansion: false
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
mountOptions:
  - read_ahead_kb=8192
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hyperdisk
spec:
  storageClassName: hyperdisk-ml
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi


