apiVersion: v1
kind: Service
metadata:
  name: mysql-svc-tuned
  namespace: mysql-tuned
  labels:
    app: mysql-app-tuned
spec:
  clusterIP: None
  ports:
    - name: '3306'
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql-app-tuned
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: mysql-tuned
  labels:
    app: mysql
data:
  # Basic auth and SSL settings.
  default-auth.cnf: |
    [mysqld]
    ssl-ca=/etc/mysql/ssl/ca.pem
    ssl-cert=/etc/mysql/ssl/server-cert.pem
    ssl-key=/etc/mysql/ssl/server-key.pem
    require_secure_transport = ON
    secure_file_priv = ""
    innodb_buffer_pool_size = 100G
    innodb_redo_log_capacity = 120G
    # max_prepared_stmt_count = 1048576

    # Optimization 26.06
    # general
    max_connections=4000
    table_open_cache=8000
    table_open_cache_instances=16
    max_prepared_stmt_count=512000
    back_log=1500
    # default_password_lifetime=0
    # default_authentication_plugin=mysql_native_password
    # character_set_server=latin1
    # collation_server=latin1_swedish_ci
    skip-character-set-client-handshake
    performance_schema=OFF
    skip_log_bin=1
    transaction_isolation=REPEATABLE-READ

    # files
    innodb_file_per_table
    innodb_log_file_size=1024M
    innodb_log_files_in_group=32
    innodb_open_files=4000

    # buffers
    innodb_buffer_pool_instances=16
    innodb_log_buffer_size=64M

    # tune
    innodb_doublewrite=0
    innodb_thread_concurrency=0
    innodb_flush_log_at_trx_commit=1
    innodb_max_dirty_pages_pct=90
    innodb_max_dirty_pages_pct_lwm=10

    join_buffer_size=32K
    sort_buffer_size=32K
    innodb_use_native_aio=1
    innodb_stats_persistent=1
    innodb_spin_wait_delay=6

    innodb_max_purge_lag_delay=300000
    innodb_max_purge_lag=0
    innodb_flush_method=O_DIRECT
    innodb_checksum_algorithm=none
    innodb_io_capacity=10000
    innodb_io_capacity_max=40000
    innodb_lru_scan_depth=9000
    innodb_change_buffering=none
    innodb_read_only=0
    innodb_page_cleaners=16
    innodb_undo_log_truncate=off

    # perf special
    innodb_adaptive_flushing=1
    innodb_flush_neighbors=0
    innodb_read_io_threads=16
    innodb_write_io_threads=16
    innodb_purge_threads=4
    innodb_adaptive_hash_index=0
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: mysql-tuned
  labels:
    app: mysql-app-tuned
spec:
  serviceName: mysql-svc-tuned
  replicas: 1
  selector:
    matchLabels:
      app: mysql-app-tuned
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Delete
  template:
    metadata:
      labels:
        app: mysql-app-tuned
    spec:
      securityContext:
        sysctls:
        - name: net.ipv4.tcp_fin_timeout
          value: "5"
        # - name: net.ipv4.tcp_tw_reuse
        #   value: "1"
        # - name: net.ipv4.tcp_max_syn_backlog
        #   value: "65535"
        # - name: net.core.somaxconn
        #   value: "65535"
      nodeSelector:
        cloud.google.com/gke-nodepool: mysql-tuned
      tolerations:
        - key: "app.stateful/component"
          operator: "Equal"
          value: "mysql-tuned"
          effect: NoSchedule
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - mysql-app-tuned
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: mysql-container
          image: mysql:8.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root-password
            - name: MYSQL_DATABASE
              value: test
            - name: MYSQL_USER
              value: bench_user
            - name: MYSQL_PASSWORD
              value: mysqlpass123
            - name: MYSQL_INITDB_SKIP_TZINFO
              value: "1"
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: mysql-config
              mountPath: /etc/mysql/conf.d
            - name: ssl-certs
              mountPath: /etc/mysql/ssl/ca.pem
              subPath: ca.pem
            - name: ssl-certs
              mountPath: /etc/mysql/ssl/server-cert.pem
              subPath: server-cert.pem
            - name: ssl-certs
              mountPath: /etc/mysql/ssl/server-key.pem
              subPath: server-key.pem
          resources:
            requests:
              memory: 100Gi
              cpu: "10"
            limits:
              memory: 116Gi
              cpu: "15"
            # limits:
            #   memory: 250Gi
            #   cpu: "31"
      volumes:
        - name: mysql-config
          configMap:
            name: mysql-config
        - name: ssl-certs
          secret:
            secretName: mysql-ssl-certs
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: balanced-storage-tuned
        resources:
          requests:
            storage: "500Gi"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql-tuned
type: Opaque
data:
  root-password: bXlzcWxwYXNzMTIz