apiVersion: v1
kind: Service
metadata:
  name: mysql-svc-tuned
  namespace: mysql-tuned
  labels:
    app: mysql-app-tuned
spec:
  clusterIP: None
  ports:
    - name: '3306'
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql-app-tuned
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: mysql-tuned
  labels:
    app: mysql
data:
  # Basic auth and SSL settings.
  default-auth.cnf: |
    [mysqld]
    ssl-ca=/etc/mysql/ssl/ca.pem
    ssl-cert=/etc/mysql/ssl/server-cert.pem
    ssl-key=/etc/mysql/ssl/server-key.pem
    ssl
    require_secure_transport = ON
    default_authentication_plugin=mysql_native_password

  # Performance and operational tuning.
  performance.cnf: |
    [mysqld]
    # General & Connection Settings
    max_connections               = 4100
    back_log                      = 1500
    table_open_cache              = 200000
    table_open_cache_instances    = 32
    max_prepared_stmt_count       = 512000
    skip-name-resolve
    skip-character-set-client-handshake
    performance_schema            = 1
    binlog_row_image              = MINIMAL

    #####################
    # InnoDB settings
    #####################
    innodb_buffer_pool_size         = 100G
    innodb_buffer_pool_instances    = 16
    innodb_redo_log_capacity        = 120G
    innodb_io_capacity              = 80000
    innodb_io_capacity_max          = 1600000
    innodb_page_cleaners            = 16
    innodb_purge_threads            = 4
    innodb_lru_scan_depth           = 1024
    innodb_adaptive_flushing_lwm    = 10
    innodb_flushing_avg_loops       = 30
    innodb_flush_method             = O_DIRECT_NO_FSYNC
    # innodb_numa_interleave          = 1
    innodb_adaptive_hash_index      = 0
    innodb_change_buffering         = none

    # Durability settings
    innodb_doublewrite              = 1
    innodb_doublewrite_pages        = 64
    innodb_doublewrite_files        = 2
    innodb_flush_log_at_trx_commit  = 1
    innodb_buffer_pool_load_at_startup = 0
    innodb_buffer_pool_dump_at_shutdown = 0

    #####################
    # Logging
    #####################
    slow-query-log                  = 1
    long_query_time                 = 10
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: mysql-tuned
  labels:
    app: mysql-app-tuned
spec:
  serviceName: mysql-svc-tuned
  replicas: 1
  selector:
    matchLabels:
      app: mysql-app-tuned
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Delete
  template:
    metadata:
      labels:
        app: mysql-app-tuned
    spec:
      securityContext:
        sysctls:
        - name: net.ipv4.tcp_fin_timeout
          value: "5"
        # - name: net.ipv4.tcp_tw_reuse
        #   value: "1"
        # - name: net.ipv4.tcp_max_syn_backlog
        #   value: "65535"
        # - name: net.core.somaxconn
        #   value: "65535"
      nodeSelector:
        cloud.google.com/gke-nodepool: mysql-tuned
      tolerations:
        - key: "app.stateful/component"
          operator: "Equal"
          value: "mysql-tuned"
          effect: NoSchedule
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - mysql-app-tuned
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: mysql-container
          image: mysql:8.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root-password
            - name: MYSQL_DATABASE
              value: test
            - name: MYSQL_USER
              value: bench_user
            - name: MYSQL_PASSWORD
              value: mysqlpass123
            - name: MYSQL_INITDB_SKIP_TZINFO
              value: "1"
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: mysql-config
              mountPath: /etc/mysql/conf.d
            - name: ssl-certs
              mountPath: /etc/mysql/ssl/ca.pem
              subPath: ca.pem
            - name: ssl-certs
              mountPath: /etc/mysql/ssl/server-cert.pem
              subPath: server-cert.pem
            - name: ssl-certs
              mountPath: /etc/mysql/ssl/server-key.pem
              subPath: server-key.pem
          resources:
            requests:
              memory: 100Gi
              cpu: "10"
            limits:
              memory: 116Gi
              cpu: "15"
      volumes:
        - name: mysql-config
          configMap:
            name: mysql-config
        - name: ssl-certs
          secret:
            secretName: mysql-ssl-certs
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: balanced-storage-base
        resources:
          requests:
            storage: "500Gi"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql-tuned
type: Opaque
data:
  root-password: bXlzcWxwYXNzMTIz