---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-sysbench
  namespace: mysql
spec:
  serviceName: mysql-svc
  replicas: 1
  selector:
    matchLabels:
      app: mysql-sysbench
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Delete
  template:
    metadata:
      labels:
        app: mysql-sysbench
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: pool-sysbench
      tolerations:
        - key: "app.stateful/component"
          operator: "Equal"
          value: "mysql-sysbench"
          effect: NoSchedule
      containers:
        - name: sysbench-container
          image: us-central1-docker.pkg.dev/hl2-gogl-wopt-t1iylu/mysql/sysbench:ubuntu24
          imagePullPolicy: Always
          securityContext:
            runAsUser: 0
            privileged: true
            allowPrivilegeEscalation: true
          command: ["/bin/sh"]
          args:
            - -c
            - |
              ulimit -n 100000 || echo "Could not set ulimit";
              apt-get update && apt-get install -y ca-certificates
              THREADS=$(THREADS)
              HOST="mysql-svc-$(ID).mysql.svc.cluster.local"

                echo "-----Prepare Tables-----"
                sysbench \
                  oltp_read_write \
                  --mysql-host=$HOST \
                  --mysql-user=bench_user \
                  --mysql-password=mysqlpass123 \
                  --mysql-db=test \
                  --mysql-ignore-errors=all \
                  --tables=8 \
                  --table-size=50000000 \
                  --threads=$THREADS \
                  --time=300 \
                  --report-interval=1 \
                  --skip-trx=on \
                  --db-driver=mysql \
                  prepare

                echo "-----Run Test-----"
                sysbench \
                  oltp_read_write \
                  --mysql-host=$HOST \
                  --mysql-user=bench_user \
                  --mysql-password=mysqlpass123 \
                  --mysql-db=test \
                  --mysql-ignore-errors=all \
                  --tables=8 \
                  --table-size=50000000 \
                  --threads=$THREADS \
                  --time=300 \
                  --report-interval=1 \
                  --skip-trx=on \
                  --db-driver=mysql \
                  run

              done;
              while true; do sleep 10; done
          volumeMounts:
            - name: mysql-ssl-certs
              mountPath: /etc/mysql/certs
              readOnly: true
      volumes:
        - name: mysql-ssl-certs
          secret:
            secretName: mysql-ssl-certs