apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  labels:
    app: kafka-app
spec:
  clusterIP: None
  ports:
    - name: '9092'
      port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    app: kafka-app
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    app: kafka-app
spec:
  serviceName: kafka-svc
  replicas: 1
  selector:
    matchLabels:
      app: kafka-app
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Delete
  template:
    metadata:
      labels:
        app: kafka-app
    spec:
      tolerations:
      - key: "app.stateful/component"
        operator: "Equal"
        value: "kafka-tuned"
        effect: NoSchedule
      - key: "kubernetes.io/arch"
        operator: "Equal"
        value: arm64
        effect: NoSchedule
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: "app.stateful/component"
                operator: In
                values:
                - "kafka-tuned"
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - {{ZONE}}
      nodeSelector:
        cloud.google.com/gke-nodepool: kafka-tuned
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "topology.kubernetes.io/zone"
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: kafka-app
      containers:
        - name: kafka-container
          image: us-central1-docker.pkg.dev/hl2-gogl-wopt-t1iylu/kafka-repo/kafka:3.9.0-arm
          imagePullPolicy: Always
          ports:
            - containerPort: 9092
            - containerPort: 9093
          env:
            - name: REPLICAS
              value: '1'
            - name: SERVICE
              value: kafka-svc
            - name: NAMESPACE
              value: kafka-tuned
            - name: SHARE_DIR
              value: /mnt/kafka
            - name: CLUSTER_ID
              value: hTo9UNhMX9pjNTbHeFeA
            - name: DEFAULT_REPLICATION_FACTOR
              value: '1'
            - name: DEFAULT_MIN_INSYNC_REPLICAS
              value: '0'
          volumeMounts:
            - name: data
              mountPath: /mnt/kafka
          resources:
            requests:
              memory: 10Gi
              cpu: "1"
            limits:
              memory: 15Gi
              cpu: "2"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        storageClassName: balanced-storage-tuned
        resources:
          requests:
            storage: "300Gi"
