apiVersion: v1
kind: Pod
metadata:
  name: kafka-perftest
  namespace: kafka
spec:
  containers:
  - name: kafka-perftest
    image: us-central1-docker.pkg.dev/hl2-gogl-wopt-t1iylu/kafka-repo/kafka:3.9.0
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 10;done"]
  restartPolicy: Always
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - {{ZONE}}
  nodeSelector:
    cloud.google.com/gke-nodepool: pool-perftest
