apiVersion: v1
kind: Pod
metadata:
  name: kafka-perftest
  namespace: kafka
spec:
  containers:
  - name: kafka-perftest
    image: us-central1-docker.pkg.dev/hl2-gogl-wopt-t1iylu/kafka-repo/kafka:3.9.0
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 10;done"]
  restartPolicy: Always
  # tolerations:
  # - key: "app.stateful/component"
  #   operator: "Equal"
  #   value: "kafka-perftest"
  #   effect: NoSchedule
  nodeSelector:
    cloud.google.com/gke-nodepool: pool-perftest
