---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
      labels:
        app: vllm
    spec:
      serviceAccountName: bucket-sa
      containers:
      - command: [ "/bin/sh", "-c" ]
        args: [ "vllm serve /data/Llama-4-Scout-17B-16E --served-model-name=llama --tensor-parallel-size=4" ]
        image: vllm/vllm-openai:v0.8.5
        name: inference-server
        resources:
          limits:
            cpu: '80'
            memory: 800Gi
            nvidia.com/gpu: '4'
          requests:
            cpu: '80'
            memory: 800Gi
            nvidia.com/gpu: '4'
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - name: gcs-fuse-csi-ephemeral
          mountPath: /data
          readOnly: true
      tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Equal
        value: present
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-h100-80gb
        cloud.google.com/gke-spot: "true"
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: gcs-fuse-csi-ephemeral
        csi:
          driver: gcsfuse.csi.storage.gke.io
          readOnly: true
          volumeAttributes:
            bucketName: epam-team-huggingface
            gcsfuseLoggingSeverity: warning
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-endpoint
spec:
  selector:
    app: vllm
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

