apiVersion: v1
kind: Pod
metadata:
  name: pg-client-tls
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"

spec:
  restartPolicy: Never
  containers:
  - name: pg-client
    image: postgres:15-alpine
    command: ["sleep", "100000"]
    env:
    - name: CLIENTPASSWORD
      valueFrom:
        secretKeyRef:
          name: gke-pg-cluster-app
          key: password
    - name: CLIENTUSERNAME
      valueFrom:
        secretKeyRef:
          name: gke-pg-cluster-app
          key: username
    volumeMounts:
      - name: secret-volume-root-ca
        mountPath: /etc/secrets/ca
  volumes:
    - name: secret-volume-root-ca
      secret:
        secretName: my-postgres-server-ca
        defaultMode: 0600
