apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: balanced-storage-base
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: gp3
  fsType: xfs
  iops: "16000"
  throughput: "1000"
reclaimPolicy: Delete