apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: balanced-storage-base
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: io2
  fsType: xfs
  iops: "50000"
reclaimPolicy: Delete