apiVersion: v1
kind: Secret
metadata:
  name: mysql-ssl-certs-tuned
  namespace: mysql-tuned
type: Opaque
data:
  ca.pem: #Key placeholder
  server-cert.pem: #Key placeholder
  server-key.pem: #Key placeholder
  client-cert.pem: #Key placeholder
  client-key.pem: #Key placeholder