apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: mysql
  labels:
    app: mysql-app
spec:
  clusterIP: None
  ports:
    - name: '3306'
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql-app