---
apiVersion: v1
kind: Pod
metadata:
  name: kafkacat
spec:
  containers:
  - name: kafkacat
    image: confluentinc/cp-kcat:7.4.0
    command: ["sh", "-c", "exec tail -f /dev/null"]
    volumeMounts:
    - name: source-user
      mountPath: "/source-user"
      readOnly: true
    - name: target-user
      mountPath: "/target-user"
      readOnly: true
    - name: config-volume
      mountPath: /home/appuser/.config
  volumes:
  - name: source-user
    secret:
      secretName: source-user
  - name: target-user
    secret:
      secretName: target-user
  - name: config-volume
    configMap:
      name: kcat-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kcat-config
data:
  kcat.conf: enable.ssl.certificate.verification=false
