apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: my-mirror-maker-2
spec:
  version: 3.4.0
  replicas: 1
  connectCluster: "my-target-cluster"
  clusters:
  - alias: "my-source-cluster"
    bootstrapServers: my-source-cluster-kafka-bootstrap.kafka.svc.strimzi-source.local:9093
    tls:
      trustedCertificates:
        - secretName: my-source-cluster-cluster-ca-cert
          certificate: ca.crt
    authentication:
        type: tls
        certificateAndKey:
          secretName: source-user
          certificate: user.crt
          key: user.key
  - alias: "my-target-cluster"
    bootstrapServers: my-target-cluster-kafka-bootstrap.kafka.svc.strimzi-target.local:9093
    tls:
      trustedCertificates:
        - secretName: my-target-cluster-cluster-ca-cert
          certificate: ca.crt
    authentication:
        type: tls
        certificateAndKey:
          secretName: target-user
          certificate: user.crt
          key: user.key
    config:
      config.storage.replication.factor: -1
      offset.storage.replication.factor: -1
      status.storage.replication.factor: -1
  mirrors:
  - sourceCluster: "my-source-cluster"
    targetCluster: "my-target-cluster"
    sourceConnector:
      tasksMax: 1
      config:
        replication.factor: 3
        offset-syncs.topic.replication.factor: 3
        sync.topic.acls.enabled: "false"
    checkpointConnector:
      tasksMax: 1
      config:
        checkpoints.topic.replication.factor: 3
        sync.group.offsets.enabled: "true"
    topicsPattern: ".*"
    groupsPattern: ".*"
