---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sglang
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sglang
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
      labels:
        app: sglang
    spec:
      restartPolicy: Always
      serviceAccountName: bucket-sa
      containers:
      - name: sglang
        image: docker.io/lmsysorg/sglang:v0.4.7-cu124
        imagePullPolicy: Always
        ports:
        - containerPort: 30000
        command: ["python3", "-m", "sglang.launch_server"]
        args: ["--model-path", "/data/Llama-4-Scout-17B-16E", "--host", "0.0.0.0", "--port", "30000", "--tp", "4"]
        resources:
          limits:
            cpu: '80'
            memory: 800Gi
            nvidia.com/gpu: '4'
          requests:
            cpu: '80'
            memory: 800Gi
            nvidia.com/gpu: '4'
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - name: hyperdisk
          mountPath: /data
          readOnly: true
      tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Equal
        value: present
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-h100-80gb
        cloud.google.com/gke-spot: "true"
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: hyperdisk
        persistentVolumeClaim:
          claimName: hyperdisk        
---
apiVersion: v1
kind: Service
metadata:
  name: sglang-endpoint
spec:
  selector:
    app: sglang
  ports:
    - protocol: TCP
      port: 30000
      targetPort: 30000
