---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sglangl3
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sglangl3
  template:
    metadata:
      labels:
        app: sglangl3
    spec:
      restartPolicy: Always
      containers:
      - name: sglang
        image: docker.io/lmsysorg/sglang:latest-srt
        imagePullPolicy: Always 
        ports:
        - containerPort: 30000
        command: ["python3", "-m", "sglang.launch_server"]
        args: ["--model-path", "unsloth/Llama-3-8B-Instruct", "--host", "0.0.0.0", "--port", "30000", "--tp", "4"]
        resources:
          limits:
            cpu: '80'
            memory: 800Gi
            nvidia.com/gpu: '4'
          requests:
            cpu: '80'
            memory: 800Gi
            nvidia.com/gpu: '4'
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Equal
        value: present
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-h100-80gb
        cloud.google.com/gke-spot: "true"
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: sglang-endpoint-l3
spec:
  selector:
    app: sglangl3
  ports:
    - protocol: TCP
      port: 30000
      targetPort: 30000
